### ISSUE TITLE
Add handler when insight server down

### ISSUE THREAD

**Issue by cmgustavo** [bitpay/bitcore-wallet-service#154]
I got the follow error:

```
Invalid Argument: Must provide the scriptPubKey for that output!
Error
    at Error.NodeError (/Users/gustavo/Documents/github/bitcore-wallet-service/node_modules/bitcore-explorers/node_modules/bitcore/lib/errors/index.js:20:41)
    at Object.module.exports.checkArgument (/Users/gustavo/Documents/github/bitcore-wallet-service/node_modules/bitcore-explorers/node_modules/bitcore/lib/util/preconditions.js:14:13)
    at new UnspentOutput (/Users/gustavo/Documents/github/bitcore-wallet-service/node_modules/bitcore-explorers/node_modules/bitcore/lib/transaction/unspentoutput.js:44:5)
    at UnspentOutput (/Users/gustavo/Documents/github/bitcore-wallet-service/node_modules/bitcore-explorers/node_modules/bitcore/lib/transaction/unspentoutput.js:31:12)
    at Function.map (/Users/gustavo/Documents/github/bitcore-wallet-service/node_modules/bitcore-explorers/node_modules/lodash/dist/lodash.js:3508:27)
    at Request._callback (/Users/gustavo/Documents/github/bitcore-wallet-service/node_modules/bitcore-explorers/lib/insight.js:66:17)
    at Request.self.callback (/Users/gustavo/Documents/github/bitcore-wallet-service/node_modules/request/request.js:344:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/gustavo/Documents/github/bitcore-wallet-service/node_modules/request/request.js:1239:14)
    at Request.emit (events.js:117:20)
```

**Comment by matiu** [comment]
done.
