### ISSUE TITLE
Post how to setup https in installation.md

### ISSUE THREAD

**Issue by dabura667** [bitpay/bitcore-wallet-service#237]
I have a trusted root certificate, and no matter what I do I still can't get an https connection running.

A step by step, including maybe any specific methods you may have used to convert popular formats into the format you use for bws.

This will at least help me figure out if I'm going crazy or not.

**Comment by matiu** [comment]
Hey,

This is the setup we have at bitpay's servers, at config.js
```
  https: true,
  privateKeyFile: '/etc/ssl/bws.bitpay.com.key',
  certificateFile: '/etc/ssl/bws.bitpay.com.crt',
```
```
# cat /etc/ssl/bws.bitpay.com.key
-----BEGIN RSA PRIVATE KEY-----
[...]
-----END RSA PRIVATE KEY-----

# cat /etc/ssl/bws.bitpay.com.crt 
-----BEGIN CERTIFICATE-----
[...]
-----END CERTIFICATE-----
```

hope it helps.

**Comment by dabura667** [comment]
The example in the config.js says PEM...

Should the file be in PEM format with key and crt extensions?

I currently have PEM format with .pem extensions for both of them.

**Comment by matiu** [comment]
Yes, PEM is the right format.

We are using node's https module. See the detailed documentation here:
https://nodejs.org/api/https.html

On Mon, Jun 8, 2015 at 12:47 PM, dabura667 <notifications@github.com> wrote:

> The example in the config.js says PEM...
>
> Should the file be in PEM format with key and crt extensions?
>
> I currently have PEM format with .pem extensions for both of them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/bitcore-wallet-service/issues/237#issuecomment-110050144>
> .
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by dabura667** [comment]
OK, still not working.

Here's what I did, maybe someone with more experience in SSL than me can advise:

1. `openssl genrsa -out /etc/ssl/bws.key 2048`
2. `openssl req -new -sha256 -key /etc/ssl/bws.key -out /etc/ssl/bws.csr`
3. Set up CSR using my country JP. my common name = domain name. etc etc.
4. On namecheap, I go to reissue SSL and paste in my csr
5. I get verification e-mails etc. and eventually I get a zip file with 4 crt files.
    * AddTrustExternalCARoot.crt
    * COMODORSAAddTrustCA.crt
    * COMODORSADomainValidationSecureServerCA.crt
    * www_mydomain_com.crt
6. I copy the contents of www_mydomain_com.crt and use `sudo vi bws.crt` to write it into a new file in /etc/ssl along with the others.
7. Once I have the crt and key file, I change config.js in the bws directory to say this:
```javascript
https: true,
privateKeyFile: '/etc/ssl/bws.key',
certificateFile: '/etc/ssl/bws.crt',
```
8. I run everything as normal. (as when I run http, which works fine)
9. Copay doesn't connect.

Bonus: `curl -vk https://<myip>:3232/bws/api/` returns a {"BAD SIGNATURE"} response and adding the proper headers from a successful request returns the wallet data. (-k being "insecure mode" where it doesn't verify CAs)

My Copay version is v1.0.1 Android. But I have tried with all my clients. Windows, iPhone, Android and they are fine.

I used to get a CORS error, but now I don't. I just get {"CONNERR"} in my Copay logs.
BWS logs show no log of my attempts at connecting.

A couple things I am wondering:
1. Do I need to do something with the other 3 crt files?
2. Does Copay view my CA as a trust worthy CA? (PositiveSSL by Comodo Security Services)
3. Does Copay disallow https connections not routed to port 443? (I can't use 443 right now)

**Comment by matiu** [comment]
I think the problem is you are not using 443. IIRC we run into this before.
There could be a bug in bws that it not using the correct port.

Could you check telnet to 3232 an see if you get a response?

On Tue, Jun 9, 2015 at 11:42 AM, dabura667 <notifications@github.com> wrote:

> OK, still not working.
>
> Here's what I did, maybe someone with more experience in SSL than me can
> advise:
>
>    1. openssl genrsa -out /etc/ssl/bws.key 2048
>    2. openssl req -new -sha256 -key /etc/ssl/bws.key -out /etc/ssl/bws.csr
>    3. Set up CSR using my country JP. my common name = domain name. etc
>    etc.
>    4. On namecheap, I go to reissue SSL and paste in my csr
>    5. I get verification e-mails etc. and eventually I get a zip file
>    with 4 crt files.
>       - AddTrustExternalCARoot.crt
>       - COMODORSAAddTrustCA.crt
>       - COMODORSADomainValidationSecureServerCA.crt
>       - www_mydomain_com.crt
>     6. I copy the contents of www_mydomain_com.crt and use sudo vi bws.crt
>    to write it into a new file in /etc/ssl along with the others.
>    7. Once I have the crt and key file, I change config.js in the bws
>    directory to say this:
>
> https: true,
> privateKeyFile: '/etc/ssl/bws.key',
> certificateFile: '/etc/ssl/bws.crt',
>
>
>    1. I run everything as normal. (as when I run http, which works fine)
>    2. Copay doesn't connect.
>
> Bonus: curl -vk https://<myip>:3232/bws/api/ returns a {"BAD SIGNATURE"}
> response and adding the proper headers from a successful request returns
> the wallet data. (-k being "insecure mode" where it doesn't verify CAs)
>
> My Copay version is v1.0.1 Android. But I have tried with all my clients.
> Windows, iPhone, Android and they are fine.
>
> I used to get a CORS error, but now I don't. I just get {"CONNERR"} in my
> Copay logs.
> BWS logs show no log of my attempts at connecting.
>
> A couple things I am wondering:
> 1. Do I need to do something with the other 3 crt files?
> 2. Does Copay view my CA as a trust worthy CA? (PositiveSSL by Comodo
> Security Services)
> 3. Does Copay disallow https connections not routed to port 443? (I can't
> use 443 right now)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/bitcore-wallet-service/issues/237#issuecomment-110385992>
> .
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by matiu** [comment]
oh, sorry, you said you hace used curl successfully.


On Tue, Jun 9, 2015 at 11:49 AM, Matias Alejo Garcia <ematiu@gmail.com>
wrote:

> I think the problem is you are not using 443. IIRC we run into this
> before. There could be a bug in bws that it not using the correct port.
>
> Could you check telnet to 3232 an see if you get a response?
>
> On Tue, Jun 9, 2015 at 11:42 AM, dabura667 <notifications@github.com>
> wrote:
>
>> OK, still not working.
>>
>> Here's what I did, maybe someone with more experience in SSL than me can
>> advise:
>>
>>    1. openssl genrsa -out /etc/ssl/bws.key 2048
>>    2. openssl req -new -sha256 -key /etc/ssl/bws.key -out
>>    /etc/ssl/bws.csr
>>    3. Set up CSR using my country JP. my common name = domain name. etc
>>    etc.
>>    4. On namecheap, I go to reissue SSL and paste in my csr
>>    5. I get verification e-mails etc. and eventually I get a zip file
>>    with 4 crt files.
>>       - AddTrustExternalCARoot.crt
>>       - COMODORSAAddTrustCA.crt
>>       - COMODORSADomainValidationSecureServerCA.crt
>>       - www_mydomain_com.crt
>>     6. I copy the contents of www_mydomain_com.crt and use sudo vi
>>    bws.crt to write it into a new file in /etc/ssl along with the others.
>>    7. Once I have the crt and key file, I change config.js in the bws
>>    directory to say this:
>>
>> https: true,
>> privateKeyFile: '/etc/ssl/bws.key',
>> certificateFile: '/etc/ssl/bws.crt',
>>
>>
>>    1. I run everything as normal. (as when I run http, which works fine)
>>    2. Copay doesn't connect.
>>
>> Bonus: curl -vk https://<myip>:3232/bws/api/ returns a {"BAD SIGNATURE"}
>> response and adding the proper headers from a successful request returns
>> the wallet data. (-k being "insecure mode" where it doesn't verify CAs)
>>
>> My Copay version is v1.0.1 Android. But I have tried with all my clients.
>> Windows, iPhone, Android and they are fine.
>>
>> I used to get a CORS error, but now I don't. I just get {"CONNERR"} in my
>> Copay logs.
>> BWS logs show no log of my attempts at connecting.
>>
>> A couple things I am wondering:
>> 1. Do I need to do something with the other 3 crt files?
>> 2. Does Copay view my CA as a trust worthy CA? (PositiveSSL by Comodo
>> Security Services)
>> 3. Does Copay disallow https connections not routed to port 443? (I can't
>> use 443 right now)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/bitpay/bitcore-wallet-service/issues/237#issuecomment-110385992>
>> .
>>
>
>
>
> --
> Matías Alejo Garcia
> @ematiu
> Roads? Where we're going, we don't need roads!
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by dabura667** [comment]
can I change BWS to 443 in config.js?

Should I try to reroute 443 to 3232 in Apache via Virtual Network?

**Comment by dabura667** [comment]
Changing BWS port to 443 says I can't start because of conflicting port.

I think it's because of my apache server...

Let me look up how to re-route 443 incoming connections to 3232 internally... I hope this works.

Keep me updated if anyone figures out what my problem is.

**Comment by dabura667** [comment]
```
> bitcore-wallet-service@0.0.33 start /home/dabs/bitcore-wallet-service
> node bws.js

info Using locker server:localhost:3231
info Using message broker server at http://localhost:3380
Connection established to  mongodb://localhost:27017/bws
info Using message broker server at http://localhost:3380

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1024:19)
    at listen (net.js:1065:10)
    at Server.listen (net.js:1139:5)
    at /home/dabs/bitcore-wallet-service/bws.js:79:10
    at /home/dabs/bitcore-wallet-service/bws.js:63:14
    at /home/dabs/bitcore-wallet-service/bws.js:50:22
    at /home/dabs/bitcore-wallet-service/node_modules/async/lib/async.js:251:17
    at done (/home/dabs/bitcore-wallet-service/node_modules/async/lib/async.js:132:19)
    at /home/dabs/bitcore-wallet-service/node_modules/async/lib/async.js:32:16
npm ERR! weird error 8
npm ERR! not ok code 0
info Connected to insight (livenet) @ https://insight.bitpay.com:443
```
This is what I get when I try to run BWS on port 443

**Comment by dabura667** [comment]
http://www.benjiegillam.com/2012/06/node-dot-js-ssl-certificate-chain/

looks like nodejs https module doesn't store COMODO as a trusted root cert.

I will try adding the certs later

**Comment by dabura667** [comment]
I figured out the problem:

1. I needed to set up the `ca` parameter in httpsOptions for https.
```javascript
// config.js
  https: true,
  privateKeyFile: './ssl/bwsreal.key',
  certificateFile: './ssl/bwsreal.crt',
  CAsecserver: './ssl/SecureServer.crt',
  CAtrust: './ssl/AddTrustCA.crt',
  CAroot: './ssl/CAroot.crt',

// bws.js
if (config.https) {
  serverOpts.key = fs.readFileSync(config.privateKeyFile || './ssl/privatekey.pem');
  serverOpts.cert = fs.readFileSync(config.certificateFile || './ssl/certificate.pem');

  if (config.CAsecserver && config.CAtrust && config.CAroot) {
    serverOpts.ca = [fs.readFileSync(config.CAsecserver),
                     fs.readFileSync(config.CAtrust),
                     fs.readFileSync(config.CAroot)
                    ];};
}
```
2. my cert has domain control enabled, so I must access it through www.mydomain.com and I was accessing through a subdomain bws.mydomain.com.

By fixing the two issues above, I was able to set up https connection to my bws...

Perhaps writing something similar to what I did above, and by default commenting out the 3 CA configs with a comment saying "If your root certificate is not showing as trusted, uncomment these and plug in your intermediate and root CA certs."

In fact, by using this, I believe we could do default to self-signed ssl. #217

**Comment by matiu** [comment]
Great to hear. Thanks a lot for sharing.

Could you send a PR to the config.js with your comments? (adding CA*
commented).

On Wed, Jun 10, 2015 at 9:06 AM, dabura667 <notifications@github.com> wrote:

> I figured out the problem:
>
>    1. I needed to set up the ca parameter in httpsOptions for https.
>
> // config.js
>   https: true,
>   privateKeyFile: './ssl/bwsreal.key',
>   certificateFile: './ssl/bwsreal.crt',
>   CAsecserver: './ssl/SecureServer.crt',
>   CAtrust: './ssl/AddTrustCA.crt',
>   CAroot: './ssl/CAroot.crt',
> // bws.jsif (config.https) {
>   serverOpts.key = fs.readFileSync(config.privateKeyFile || './ssl/privatekey.pem');
>   serverOpts.cert = fs.readFileSync(config.certificateFile || './ssl/certificate.pem');
>
>   if (config.CAsecserver && config.CAtrust && config.CAroot) {
>     serverOpts.ca = [fs.readFileSync(config.CAsecserver),
>                      fs.readFileSync(config.CAtrust),
>                      fs.readFileSync(config.CAroot)
>                     ];};
> }
>
>
>    1. my cert has domain control enabled, so I must access it through
>    www.mydomain.com and I was accessing through a subdomain
>    bws.mydomain.com.
>
> By fixing the two issues above, I was able to set up https connection to
> my bws...
>
> Perhaps writing something similar to what I did above, and by default
> commenting out the 3 CA configs with a comment saying "If your root
> certificate is not showing as trusted, uncomment these and plug in your
> intermediate and root CA certs."
>
> In fact, by using this, I believe we could do default to self-signed ssl.
> #217 <https://github.com/bitpay/bitcore-wallet-service/issues/217>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/bitcore-wallet-service/issues/237#issuecomment-110721163>
> .
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by dabura667** [comment]
#243 added

**Comment by matiu** [comment]
great!

On Wed, Jun 10, 2015 at 10:34 AM, dabura667 <notifications@github.com>
wrote:

> #243 <https://github.com/bitpay/bitcore-wallet-service/pull/243> added
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/bitcore-wallet-service/issues/237#issuecomment-110754631>
> .
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!
