### ISSUE TITLE
bcmonitor startup is failing on HEAD

### ISSUE THREAD

**Issue by rajeshjayaraman** [bitpay/bitcore-wallet-service#251]
Starting up bcmonitor is failing on the latest version of HEAD. It looks like a new object Insight has been introduced that does not contain the field provider.

```
[rajesh@rjmbp] ~/Plank/src/contrib/bitcore-wallet-service$ node bcmonitor/bcmonitor.js
/Users/rajesh/Plank/src/contrib/bitcore-wallet-service/lib/blockchainmonitor.js:71
eckArgument(explorer.provider == 'insight', 'Blockchain monitor ' + provider +
                                                                    ^
ReferenceError: provider is not defined
    at BlockchainMonitor._initExplorer (/Users/rajesh/Plank/src/contrib/bitcore-wallet-service/lib/blockchainmonitor.js:71:75)
    at /Users/rajesh/Plank/src/contrib/bitcore-wallet-service/lib/blockchainmonitor.js:39:14
    at arrayMap (/Users/rajesh/Plank/src/contrib/bitcore-wallet-service/node_modules/lodash/index.js:1431:25)
    at Function.map (/Users/rajesh/Plank/src/contrib/bitcore-wallet-service/node_modules/lodash/index.js:6693:14)
    at async.parallel.self.storage (/Users/rajesh/Plank/src/contrib/bitcore-wallet-service/lib/blockchainmonitor.js:26:26)
    at /Users/rajesh/Plank/src/contrib/bitcore-wallet-service/node_modules/async/lib/async.js:567:21
    at /Users/rajesh/Plank/src/contrib/bitcore-wallet-service/node_modules/async/lib/async.js:246:17
    at /Users/rajesh/Plank/src/contrib/bitcore-wallet-service/node_modules/async/lib/async.js:122:13
    at _each (/Users/rajesh/Plank/src/contrib/bitcore-wallet-service/node_modules/async/lib/async.js:46:13)
    at async.each (/Users/rajesh/Plank/src/contrib/bitcore-wallet-service/node_modules/async/lib/async.js:121:9)
```

**Comment by isocolsky** [comment]
Thanks for reporting!

**Comment by rajeshjayaraman** [comment]
Thank you for the quick fix!
