### ISSUE TITLE
Handle errors on web sockets handshake

### ISSUE THREAD

**Issue by isocolsky** [bitpay/bitcore-wallet-service#381]
If BWS is not finished initializing, this line:
https://github.com/bitpay/bitcore-wallet-service/blob/production/lib/server.js#L175
will throw an exception when invoked from the `wsapp` component.
We should:
1) convert exceptions to asynchronous errors.
2) have a retry loop in BWC if receiving `unauthorized` from the server.

For reference, this is the callstack of the error:

```
Missing error handler on 'socket'.
Error: Server not initialized
    at new WalletService (/opt/bws/bitcore-wallet-service/lib/server.js:44:11)
    at Function.WalletService.getInstanceWithAuth (/opt/bws/bitcore-wallet-service/lib/server.js:175:16)
    at Socket.<anonymous> (/opt/bws/bitcore-wallet-service/lib/wsapp.js:48:25)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.onevent (/opt/bws/bitcore-wallet-service/node_modules/socket.io/lib/socket.js:330:8)
    at Socket.onpacket (/opt/bws/bitcore-wallet-service/node_modules/socket.io/lib/socket.js:290:12)
    at Client.ondecoded (/opt/bws/bitcore-wallet-service/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/opt/bws/bitcore-wallet-service/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/opt/bws/bitcore-wallet-service/node_modules/socket.io/node_modules/socket.io-parser/index.js:247:12)
    at Client.ondata (/opt/bws/bitcore-wallet-service/node_modules/socket.io/lib/client.js:175:18)
```

**Comment by isocolsky** [comment]
Considering BWS notifications are migrating away from socket.io, this small issue is not relevant anymore.
