### ISSUE TITLE
TxProposal < v3 no longer supported

### ISSUE THREAD

**Issue by chrisrico** [bitpay/bitcore-wallet-service#566]
I upgraded to 3.1.2 (latest in NPM) last night, as well as updated my program to use the latest version of bitcore-wallet-client (3.0.0). Today after a payment proposal was created using the client, Bitcore got stuck in a shutdown loop (I have it configured as an Upstart service) with the following error:

```
[2016-08-17T16:23:33.790Z] info: ::ffff:127.0.0.1 web socket subscribe: inv
[2016-08-17T16:23:35.194Z] info: ::ffff:127.0.0.1 "POST /insight-api/addrs/utxo" 200 16996 474.648 "bws-1.9.1" 
[2016-08-17T16:23:35.222Z] error: uncaught exception: [Error: TxProposal < v3 no longer supported.]
[2016-08-17T16:23:35.231Z] error: Error: TxProposal < v3 no longer supported.
    at Function.TxProposal.fromObj (/home/bitcoin/bitcore-node/node_modules/bitcore-wallet-service/lib/model/txproposal.js:70:11)
    at /home/bitcoin/bitcore-node/node_modules/bitcore-wallet-service/lib/storage.js:332:31
    at arrayMap (/home/bitcoin/bitcore-node/node_modules/bitcore-wallet-service/node_modules/lodash/index.js:1406:25)
    at Function.map (/home/bitcoin/bitcore-node/node_modules/bitcore-wallet-service/node_modules/lodash/index.js:6710:14)
    at /home/bitcoin/bitcore-node/node_modules/bitcore-wallet-service/lib/storage.js:331:17
    at handleCallback (/home/bitcoin/bitcore-node/node_modules/bitcore-wallet-service/node_modules/mongodb/lib/utils.js:96:12)
    at /home/bitcoin/bitcore-node/node_modules/bitcore-wallet-service/node_modules/mongodb/lib/cursor.js:858:16
    at handleCallback (/home/bitcoin/bitcore-node/node_modules/bitcore-wallet-service/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:156:5)
    at setCursorDeadAndNotified (/home/bitcoin/bitcore-node/node_modules/bitcore-wallet-service/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:496:3)
    at nextFunction (/home/bitcoin/bitcore-node/node_modules/bitcore-wallet-service/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:640:7)
[2016-08-17T16:23:35.232Z] info: Beginning shutdown

```

**Comment by chrisrico** [comment]
It's now crashing every time I try to query the proposals, for instance if I start up Copay.

**Comment by isocolsky** [comment]
Hi, sorry about this, it is a known issue already fixed in the master branch. We just published v1.10.0, please check it out and let us know if you still have this issue.

**Comment by chrisrico** [comment]
How would I upgrade just bitcore-wallet-service? I'm running Bitcore v4.1.0.
