### ISSUE TITLE
Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.

### ISSUE THREAD

**Issue by Lalitpatadiya12** [bitpay/bitcore-wallet-service#703]
/root/bitcore/node_modules/bitcore-wallet-service/node_modules/bitcore-lib/index.js:16
    throw new Error(message);
    ^

Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.
    at Object.bitcore.versionGuard (/root/bitcore/node_modules/bitcore-wallet-service/node_modules/bitcore-lib/index.js:16:11)
    at Object.<anonymous> (/root/bitcore/node_modules/bitcore-wallet-service/node_modules/bitcore-lib/index.js:20:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/bitcore/node_modules/bitcore-wallet-service/bitcorenode/index.js:10:15)
    at Module._compile (module.js:409:26)

**Comment by apollomatheus** [comment]
You can delete this folder 'bitcore-wallet-service/node_modules/bitcore-lib'
If you already have one in /root/bitcore/node_modules
