### ISSUE TITLE
Unable to connect to the mongoDB when "npm start"

### ISSUE THREAD

**Issue by Ankarrr** [bitpay/bitcore-wallet-service#739]
I make the command "npm start", but I can't connect http://localhost:3232/bws/api. The logs tell me "Unable to connect to the mongoDB", so what should I do? I try start "mongod", but it still doesn't work.

bws.log:

```
nfo Listening on port: 3232 
info Limiting wallet creation per IP: 15 req/h
info Limiting estimate fee per IP: 60 req/h
info Using locker server:localhost:3231 
ERR! Unable to connect to the mongoDB. Check the credentials. 
ERR! Could not initialize MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
ERR! Could not initialize     at Pool.<anonymous> (/Users/anderson0817/cepave/bitcore-wallet-service/node_modules/mongodb-core/lib/topologies/server.js:336:35)
ERR! Could not initialize     at emitOne (events.js:116:13)
ERR! Could not initialize     at Pool.emit (events.js:211:7)
ERR! Could not initialize     at Connection.<anonymous> (/Users/anderson0817/cepave/bitcore-wallet-service/node_modules/mongodb-core/lib/connection/pool.js:280:12)
ERR! Could not initialize     at Object.onceWrapper (events.js:317:30)
ERR! Could not initialize     at emitTwo (events.js:126:13)
ERR! Could not initialize     at Connection.emit (events.js:214:7)
ERR! Could not initialize     at Socket.<anonymous> (/Users/anderson0817/cepave/bitcore-wallet-service/node_modules/mongodb-core/lib/connection/connection.js:187:49)
ERR! Could not initialize     at Object.onceWrapper (events.js:315:30)
ERR! Could not initialize     at emitOne (events.js:116:13)
ERR! Could not initialize  { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
ERR! Could not initialize     at Pool.<anonymous> (/Users/anderson0817/cepave/bitcore-wallet-service/node_modules/mongodb-core/lib/topologies/server.js:336:35)
ERR! Could not initialize     at emitOne (events.js:116:13)
ERR! Could not initialize     at Pool.emit (events.js:211:7)
ERR! Could not initialize     at Connection.<anonymous> (/Users/anderson0817/cepave/bitcore-wallet-service/node_modules/mongodb-core/lib/connection/pool.js:280:12)
ERR! Could not initialize     at Object.onceWrapper (events.js:317:30)
ERR! Could not initialize     at emitTwo (events.js:126:13)
ERR! Could not initialize     at Connection.emit (events.js:214:7)
ERR! Could not initialize     at Socket.<anonymous> (/Users/anderson0817/cepave/bitcore-wallet-service/node_modules/mongodb-core/lib/connection/connection.js:187:49)
ERR! Could not initialize     at Object.onceWrapper (events.js:315:30)
ERR! Could not initialize     at emitOne (events.js:116:13)
ERR! Could not initialize   name: 'MongoError',
ERR! Could not initialize   message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }

/Users/anderson0817/cepave/bitcore-wallet-service/node_modules/mongodb/lib/mongo_client.js:421
          throw err
          ^
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/anderson0817/cepave/bitcore-wallet-service/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/Users/anderson0817/cepave/bitcore-wallet-service/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/Users/anderson0817/cepave/bitcore-wallet-service/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
```

**Comment by Ankarrr** [comment]
`mongod --dbpath /Users/anderson/bitcore-wallet-service/db
`
This can solve this problem.
